---
- name: Add newly deployed VM to AAP inventory
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Add host to AAP inventory
    ansible.controller.host:
      name: "{{ vm_name }}"
      inventory: 4
      state: present
      controller_host: "{{ lookup('env', 'CONTROLLER_HOST') }}"
      controller_username: "{{ lookup('env', 'CONTROLLER_USERNAME') }}"
      controller_password: "{{ lookup('env', 'CONTROLLER_PASSWORD') }}"
      validate_certs: false
      variables:
        ansible_host: "{{ vm_ip }}"
        ansible_connection: winrm
        ansible_winrm_transport: ntlm
        ansible_port: 5985
        ansible_winrm_server_cert_validation: ignore