---
- name: Add newly deployed VM to AAP inventory
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Add host to AAP inventory
    awx.awx.host:
      host:
        name: "{{ vm_name }}"
        inventory: "Windows Servers - Non-Domain Controllers"
        state: "present"
        variables:
          ansible_connection: "{{ ansible_connection }}"
          ansible_winrm_transport: "{{ ansible_winrm_transport }}"
          ansible_port: "{{ ansible_port }}"
          ansible_winrm_server_cert_validation: "{{ ansible_winrm_server_cert_validation }}"
        controller_host: "{{ lookup('env', 'CONTROLLER_HOST') }}"
        controller_username: "{{ lookup('env', 'CONTROLLER_USERNAME') }}"
        controller_password: "{{ lookup('env', 'CONTROLLER_PASSWORD') }}"
        validate_certs: false