---
- name: Use Nutanix Ansible Collection to Get Oracle Linux Template Information
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Get Oracle Linux Template Information
      nutanix.ncp.ntnx_templates_info_v2:
        nutanix_host: "{{ nutanix_host }}"
        nutanix_username: "{{ nutanix_username }}"
        nutanix_password: "{{ nutanix_password }}"
        validate_certs: "{{ validate_certs }}"
        filter: "templateName eq 'oracle-linux-9.7'"
      register: template_info
 
    - name: Save Template extId as a fact
      ansible.builtin.set_fact:
        oracle_linux_template_extId: "{{ template_info.response[0].ext_id }}"

    - name: Render cloud-init script for Oracle Linux Template
      ansible.builtin.set_fact:
        cloud_init_script: |
          #cloud-config
          hostname: jvh-oracle-linux
          fqdn: jvh-oracle-linux.example.com
          users:
          - name: ansible
            sudo: ALL=(ALL) NOPASSWD:ALL
            lock_passwd: true
          - name: adminuser
            sudo: ALL=(ALL) NOPASSWD:ALL
            lock_passwd: true
          chpasswd:
            list: |
              ansible:$6$jCR7CLYbuy4mLO3Z$Hnp5tA9wf2Wo.xg.W.nJCZYDrsLX/HXqK9B3tuhgVF2jfdQDZAEkvbR/uxwPqbARz6lzZp5EgQoCRFOktwjBC.
              adminuser:$6$jCR7CLYbuy4mLO3Z$Hnp5tA9wf2Wo.xg.W.nJCZYDrsLX/HXqK9B3tuhgVF2jfdQDZAEkvbR/uxwPqbARz6lzZp5EgQoCRFOktwjBC.
            expire: false
          ssh_pwauth: true
          growpart:
            mode: auto
            devices: ['/']
          resize_rootfs: true
          timezone: America/Los_Angeles
          runcmd:
            - systemctl enable --now sshd

    - name: Display the rendered cloud-init script
      ansible.builtin.debug:
        msg: "{{ cloud_init_script }}"

    - name: Create Nutanix VM using the Oracle Linux Template
      nutanix.ncp.ntnx_templates_deploy_v2:
        nutanix_host: "{{ nutanix_host }}"
        nutanix_username: "{{ nutanix_username }}"
        nutanix_password: "{{ nutanix_password }}"
        validate_certs: "{{ validate_certs }}"
        template_extId: "{{ oracle_linux_template_extId }}"
        override_vms_config:
          name: "jvh-oracle-linux"
          guest_customization:
            config:
              cloudinit:
                cloud_init_script:
                  user_data:
                    value: "{{ cloud_init_script | b64encode }}"
      register: deploy_result