---
- name: Make an API call
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Get Oracle Linux Template Information
      nutanix.ncp.ntnx_templates_info_v2:
        nutanix_host: "{{ nutanix_host }}"
        nutanix_username: "{{ nutanix_username }}"
        nutanix_password: "{{ nutanix_password }}"
        validate_certs: "{{ validate_certs }}
      register: template_info
 
    - name: Display Response
      ansible.builtin.debug:
        msg: "Response: {{ template_info.response }}"