---
- name: Sync constructed inventory in AAP
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Sync constructed inventory
      ansible.controller.inventory_source_update:
        name: "SQL Constructed Inventory"
        inventory: "SQL Constructed Inventory"
        wait: true
        controller_host: "{{ lookup('env', 'CONTROLLER_HOST') }}"
        controller_username: "{{ lookup('env', 'CONTROLLER_USERNAME') }}"
        controller_password: "{{ lookup('env', 'CONTROLLER_PASSWORD') }}"
        validate_certs: false
