---
- name: Sync constructed inventory in AAP
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Sync constructed inventory
      ansible.controller.inventory_source_update:
        name: "{{ aap_constructed_inventory_source }}"
        inventory: "{{ aap_constructed_inventory_name }}"
        wait: true
        controller_host: "{{ lookup('env', 'CONTROLLER_HOST') }}"
        controller_username: "{{ lookup('env', 'CONTROLLER_USERNAME') }}"
        controller_password: "{{ lookup('env', 'CONTROLLER_PASSWORD') }}"
        validate_certs: false
