- name: Make an API call
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Call Nutanix API
      ansible.builtin.uri:
        url: "https://{{ nutanix_host }}:9440/api/vmm/v4.2/ahv/config/vm-guest-customization-profiles"
        method: GET  
        user: "{{ nutanix_username }}"
        password: "{{ nutanix_password }}"
        validate_certs: "{{ validate_certs }}"
        force_basic_auth: true
        headers:
          Content-Type: "application/json"
      register: api_result
    
    - name: Display API response
      ansible.builtin.set_fact:
        gc_profile_uuid: >-
          {{ api_result.json.data |
             selectattr('name', 'equalto', 'JVHDomain') |
             map(attribute='extId') | first }}

