- name: Make an API call
  hosts: localhost
  gather_facts: false
  vars:
    vm_name: "AnsDeploy"
  tasks:
    - name: Call Nutanix API
      ansible.builtin.uri:
        url: "https://{{ nutanix_host }}:9440/api/vmm/v4.2/ahv/config/vm-guest-customization-profiles"
        method: GET  
        user: "{{ nutanix_username }}"
        password: "{{ nutanix_password }}"
        validate_certs: "{{ validate_certs }}"
        force_basic_auth: true
        headers:
          Content-Type: "application/json"
      register: api_result
    
    - name: Search API response for JVHDomain and set extId as a fact
      ansible.builtin.set_fact:
        gc_profile_uuid: >-
          {{ api_result.json.data |
             selectattr('name', 'equalto', 'JVHDomain') |
             map(attribute='extId') | first }}

    - name: Print Off the extId for JVHDomain  
      ansible.builtin.debug:
        msg: "The extId for JVHDomain is: {{ gc_profile_uuid }}"

    - name: Get VM Templates from Nutanix API
      ansible.builtin.uri:
        url: "https://{{ nutanix_host }}:9440/api/vmm/v4.2/content/templates"
        method: GET
        user: "{{ nutanix_username }}"
        password: "{{ nutanix_password }}"
        validate_certs: "{{ validate_certs }}"
        force_basic_auth: true
        headers:
          Content-Type: "application/json"
      register: templates_result

    - name: Search API response for Windows Template and set extId as a fact
      ansible.builtin.set_fact:
        windows_template_extId: >-
          {{ templates_result.json.data |
             selectattr('templateName', 'equalto', 'jvh-win2025-template') |
             map(attribute='extId') | first }}

    - name: Print Off the extId for Windows Template
      ansible.builtin.debug:
        msg: "The extId for jvh-win2025-template is: {{ windows_template_extId }}"

    - name: Get template versions
      ansible.builtin.uri:
        url: "https://{{ nutanix_host }}:9440/api/vmm/v4.2/content/templates/{{ windows_template_extId }}/versions"
        method: GET
        user: "{{ nutanix_username }}"
        password: "{{ nutanix_password }}"
        validate_certs: "{{ validate_certs }}"
        force_basic_auth: true
        headers:
          Content-Type: "application/json"
      register: template_versions

    - name: Extract active version number
      ansible.builtin.set_fact:
        template_version_name: >-
          {{ template_versions.json.data |
          selectattr('isActiveVersion', 'defined') |
          selectattr('isActiveVersion', 'equalto', true) |
          map(attribute='versionName') | first }}

    - name: Get Cluster Information
      nutanix.ncp.ntnx_clusters_info_v2:
        validate_certs: false
      register: cluster_results

    - name: Display Name and extId for each cluster
      debug:
        msg: "Cluster Name: {{ item.name }} | External ID: {{ item.ext_id }}"
      loop: "{{ cluster_results.response }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Set fact for a specific cluster ID (Optional)
      set_fact:
        target_cluster_id: "{{ item.ext_id }}"
      loop: "{{ cluster_results.response }}"
      when: item.name == "ucs-ntnx"
      no_log: true

    - name: Print targeted cluster ID
      debug:
        var: target_cluster_id
      when: target_cluster_id is defined

    - name: Deploy VM from template
      ansible.builtin.uri:
        url: "https://{{ nutanix_host }}:9440/api/vmm/v4.2/content/templates/{{ windows_template_extId }}/$actions/deploy"
        method: POST
        user: "{{ nutanix_username }}"
        password: "{{ nutanix_password }}"
        validate_certs: false
        force_basic_auth: true
        headers:
          Content-Type: "application/json"
          Ntnx-Request-Id: "{{ 999999 | random | to_uuid }}"
        body_format: json
        body:
          versionNumber: "{{ template_version_name }}"
          clusterReference: "{{ target_cluster_id }}"
          numberOfVms: 1
          overrideVmConfigMap:
            "0":
              name: "{{ vm_name }}"
              guestCustomizationProfileConfig:
                profile:
                  extId: "{{ gc_profile_uuid }}"
        status_code: 202
      register: deploy_result

    - name: Get VM extId
      ansible.builtin.uri:
        url: "https://{{ nutanix_host }}:9440/api/vmm/v4.2/vms?filter=name eq '{{ vm_name }}'"
        method: GET
        user: "{{ nutanix_username }}"
        password: "{{ nutanix_password }}"
        validate_certs: false
        force_basic_auth: true
        headers:
          Content-Type: "application/json"
      register: vm_search_result